### ISSUE TITLE
Import not found can simple fixed adding '/server' on the "@clerk/nextjs"

### ISSUE THREAD

**Issue by wilkerwalace** [clerk/clerk-nextjs-app-quickstart#15]
Attempted import error: 'clerkMiddleware' is not exported from '@clerk/nextjs' (imported as 'clerkMiddleware').
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ middleware.tsx (3:1) @ <unknown>
 ⨯ (0 , _clerk_nextjs__WEBPACK_IMPORTED_MODULE_0__.clerkMiddleware) is not a function
  1 | import { clerkMiddleware } from "@clerk/nextjs";
  2 |
  3 | export default clerkMiddleware({});
     | ^
  4 |
  5 | export const config = {
  6 |     matcher: ["/((?!.+.[w]+$|_next).*)", "/", "/(api|trpc)(.*)"],
 ⨯ middleware.tsx (3:1) @ <unknown>
 ⨯ (0 , _clerk_nextjs__WEBPACK_IMPORTED_MODULE_0__.clerkMiddleware) is not a function

**Comment by kaMatPrahlad** [comment]
I'm facing the same error in my terminal, if u find the answer please let us know

**Comment by koorukuroo** [comment]
Currently, clerk is a mess with versioning. You have to do your own versioning..
https://clerk.com/docs/quickstarts/nextjs and the current version don't match, so there's nothing to refer to.
