### ISSUE TITLE
Sign-in and sign-up routes error 

### ISSUE THREAD

**Issue by hasnainbaloch** [clerk/clerk-nextjs-app-quickstart#6]
sign-up/[[...sign-up]]/page.tsx
tried custom sign-in and sign-up it is giving error
https://clerk.com/docs/references/nextjs/custom-signup-signin-pages
_use app routes with next js 14_

**Comment by royanger** [comment]
Hi @hasnainbaloch. Sorry to hear you are issuing. This repo doesn't include sign-in or sign-up routes -- it uses our Account Portal. Please reach out to our support channels either on our Discord or through the contact form on clerk.com. Just submit or message in one of those places and we will help out.

**Comment by hasnainbaloch** [comment]
Thank you, Royanger, for your support. The issue was on my end, and I've figured it out. It turns out the problem was actually with the import of ClerkProvider.
