### ISSUE TITLE
Infinite Redirect with Next.js App Router

### ISSUE THREAD

**Issue by amateurbeekeeper** [clerk/clerk-nextjs-app-quickstart#9]
It only stops once I remove the middle-wear

**Comment by devlopersabbir** [comment]
can you show with a short video??

**Comment by amateurbeekeeper** [comment]
i fixed it by doing the following:

`cleared browser cookies and changed node version to v18.18.2
`

which i learned from reading this thread:

https://github.com/clerk/javascript/issues/1436#issuecomment-1880082783

**Comment by alamenai** [comment]
This issue should be closed.
